### ISSUE TITLE
Question : is it possible to record this info into user account ?

### ISSUE THREAD

**Issue by migmake** [sjelfull/Craft-WorldTime#1]
See title :)

**Comment by sjelfull** [comment]
This is not currently supported or planned. You probably have to create a custom plugin to do that. You can use the plugin's service to get the time for the user ip, though: https://github.com/sjelfull/Craft-WorldTime/blob/master/worldtime/services/WorldtimeService.php#L35

**Comment by migmake** [comment]
Thanks
